In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\Akshata\Downloads\grapes_new.csv")

In [3]:
df

,COLOR_INTENSITY,SHAPE,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,...,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER,SOIL_TYPE,CLASS
0,120.53,elliptical,16.73,14.23,1.71,2.43,15.6,127,2.80,3.06,...,1.04,1065,23.34,54.99,31.21,97.67,7.71,52.02,archean,High
1,112.57,elliptical,20.30,13.20,1.78,2.14,11.2,100,2.65,2.76,...,1.05,1050,23.40,51.91,31.28,99.05,7.66,48.18,archean,High
2,120.78,elliptical,20.81,13.16,2.36,2.67,18.6,101,2.80,3.24,...,1.03,1185,22.29,50.69,31.92,97.95,7.66,28.15,archean,High
3,134.17,elliptical,19.47,14.37,1.95,2.50,16.8,113,3.85,3.49,...,0.86,1480,21.28,47.72,31.79,95.46,7.21,55.95,alluvial,High
4,112.19,round,17.57,13.24,2.59,2.87,21.0,118,2.80,2.69,...,1.04,735,23.76,45.09,31.86,94.45,7.80,55.99,archean,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,102.34,elliptical,21.23,12.07,2.16,2.17,21.0,85,2.60,2.65,...,0.86,378,25.58,46.15,30.14,89.52,8.49,55.83,alluvial,Medium
190,109.80,elliptical,21.67,12.43,1.53,2.29,NaN,86,2.74,3.15,...,0.69,352,24.23,52.23,30.72,85.91,7.73,55.47,archean,Medium
191,103.86,round,22.01,11.79,2.13,2.78,28.5,92,2.13,2.24,...,0.97,466,27.62,48.98,30.46,86.31,7.57,47.57,archean,Medium
192,98.30,elliptical,21.95,12.37,1.63,2.30,24.5,88,2.22,2.45,...,0.89,342,27.54,47.72,30.01,90.60,7.15,45.91,alluvial,Medium
193,101.33,elliptical,21.60,12.04,4.30,2.38,NaN,80,2.10,1.75,...,0.79,580,25.10,55.42,30.89,88.14,6.68,52.42,archean,Medium

In [4]:
df.head()

,COLOR_INTENSITY,SHAPE,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,...,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER,SOIL_TYPE,CLASS
0,120.53,elliptical,16.73,14.23,1.71,2.43,15.6,127,2.80,3.06,...,1.04,1065,23.34,54.99,31.21,97.67,7.71,52.02,archean,High
1,112.57,elliptical,20.30,13.20,1.78,2.14,11.2,100,2.65,2.76,...,1.05,1050,23.40,51.91,31.28,99.05,7.66,48.18,archean,High
2,120.78,elliptical,20.81,13.16,2.36,2.67,18.6,101,2.80,3.24,...,1.03,1185,22.29,50.69,31.92,97.95,7.66,28.15,archean,High
3,134.17,elliptical,19.47,14.37,1.95,2.50,16.8,113,3.85,3.49,...,0.86,1480,21.28,47.72,31.79,95.46,7.21,55.95,alluvial,High
4,112.19,round,17.57,13.24,2.59,2.87,21.0,118,2.80,2.69,...,1.04,735,23.76,45.09,31.86,94.45,7.80,55.99,archean,High

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   COLOR_INTENSITY    194 non-null    float64
 1   SHAPE              194 non-null    object
 2   RIPENESS_PER       192 non-null    float64
 3   ALCOHOL_PER        191 non-null    float64
 4   MALIC_ACID_PER     194 non-null    float64
 5   ASH                194 non-null    float64
 6   ALCALINITY_OF_ASH  188 non-null    float64
 7   MAGNESIUM_MEASURE  194 non-null    int64
 8   TOTAL_PHENOLS      194 non-null    float64
 9   FLAVANOIDS         194 non-null    float64
 10  PROANTHOCYANINS    194 non-null    float64
 11  HUE                192 non-null    float64
 12  PROLINE            194 non-null    int64
 13  TEMPERATURE        194 non-null    float64
 14  AVG_HUMIDITY       194 non-null    float64
 15  FERT_NITRO_PER     194 non-null    float64
 16  WATER_O2_PER       190 non-null    float64
 17  WATER_PH           194 non-null    float64
 18  FER_P2O5_PER       194 non-null    float64
 19  SOIL_TYPE          194 non-null    object
 20  CLASS              194 non-null    object
dtypes: float64(16), int64(2), object(3)
memory usage: 32.0+ KB

In [6]:
print(df.isnull().sum())

COLOR_INTENSITY      0
SHAPE                0
RIPENESS_PER         2
ALCOHOL_PER          3
MALIC_ACID_PER       0
ASH                  0
ALCALINITY_OF_ASH    6
MAGNESIUM_MEASURE    0
TOTAL_PHENOLS        0
FLAVANOIDS           0
PROANTHOCYANINS      0
HUE                  2
PROLINE              0
TEMPERATURE          0
AVG_HUMIDITY         0
FERT_NITRO_PER       0
WATER_O2_PER         4
WATER_PH             0
FER_P2O5_PER         0
SOIL_TYPE            0
CLASS                0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns=df.columns.str.strip()

In [9]:
df.ffill(inplace=True)

In [10]:
print(df.isnull().sum())

COLOR_INTENSITY      0
SHAPE                0
RIPENESS_PER         0
ALCOHOL_PER          0
MALIC_ACID_PER       0
ASH                  0
ALCALINITY_OF_ASH    0
MAGNESIUM_MEASURE    0
TOTAL_PHENOLS        0
FLAVANOIDS           0
PROANTHOCYANINS      0
HUE                  0
PROLINE              0
TEMPERATURE          0
AVG_HUMIDITY         0
FERT_NITRO_PER       0
WATER_O2_PER         0
WATER_PH             0
FER_P2O5_PER         0
SOIL_TYPE            0
CLASS                0
dtype: int64

In [11]:
x=df.drop('CLASS',axis=1)
y=df['CLASS']

In [12]:
x.describe()

,COLOR_INTENSITY,RIPENESS_PER,ALCOHOL_PER,MALIC_ACID_PER,ASH,ALCALINITY_OF_ASH,MAGNESIUM_MEASURE,TOTAL_PHENOLS,FLAVANOIDS,PROANTHOCYANINS,HUE,PROLINE,TEMPERATURE,AVG_HUMIDITY,FERT_NITRO_PER,WATER_O2_PER,WATER_PH,FER_P2O5_PER
count,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,116.882113,21.508557,13.038454,2.335103,2.365361,19.570619,99.680412,2.296649,2.016856,1.577216,0.956866,754.164948,26.418247,50.976082,30.562216,90.349381,7.680979,42.195155
std,14.333204,2.374497,0.815124,1.118041,0.268158,3.441775,14.252749,0.634317,1.001351,0.565445,0.227370,316.093797,3.042364,3.367880,1.126867,5.438735,0.509935,10.398205
min,93.000000,16.170000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.410000,0.480000,278.000000,21.020000,44.230000,27.670000,80.360000,6.510000,20.000000
25%,105.470000,20.372500,12.370000,1.610000,2.210000,17.200000,88.000000,1.725000,1.092500,1.225000,0.790000,504.000000,24.222500,48.360000,29.932500,85.862500,7.252500,33.742500
50%,114.910000,21.800000,13.050000,1.865000,2.360000,19.500000,97.500000,2.355000,2.135000,1.545000,0.980000,675.000000,26.195000,51.145000,30.710000,90.550000,7.670000,44.820000
75%,124.060000,23.317500,13.705000,3.082500,2.547500,21.500000,107.000000,2.800000,2.875000,1.950000,1.117500,988.750000,28.737500,53.722500,31.382500,94.897500,8.127500,50.542500
max,167.000000,25.200000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,3.580000,1.710000,1680.000000,32.340000,57.950000,34.160000,99.770000,8.500000,60.870000

In [14]:
one=df.iloc[:, :4]
one['CLASS']=y
two=df.iloc[:, 4:8]
two['CLASS']=y
three=df.iloc[:,8:12]
three['CLASS']=y

In [15]:
x=pd.get_dummies(x,drop_first=True)

In [16]:
col_order_ohe=x.columns.tolist()

In [18]:
col_order_ohe

['COLOR_INTENSITY',
 'RIPENESS_PER',
 'ALCOHOL_PER',
 'MALIC_ACID_PER',
 'ASH',
 'ALCALINITY_OF_ASH',
 'MAGNESIUM_MEASURE',
 'TOTAL_PHENOLS',
 'FLAVANOIDS',
 'PROANTHOCYANINS',
 'HUE',
 'PROLINE',
 'TEMPERATURE',
 'AVG_HUMIDITY',
 'FERT_NITRO_PER',
 'WATER_O2_PER',
 'WATER_PH',
 'FER_P2O5_PER',
 'SHAPE_round',
 'SOIL_TYPE_archean']

In [19]:
from sklearn.ensemble import IsolationForest

In [20]:
iso=IsolationForest(contamination=0.05,random_state=0)

In [21]:
clean=iso.fit_predict(x)

In [22]:
clean

array([ 1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1])

In [23]:
x=x[clean==1]
y=y[clean==1]

In [24]:
x.shape

(184, 20)

In [25]:
!pip install imblearn

Collecting imblearn
  Downloading imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Downloading imbalanced_learn-0.14.2-py3-none-any.whl.metadata (8.9 kB)
Collecting numpy<3,>=1.25.2 (from imbalanced-learn->imblearn)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting scipy<2,>=1.11.4 (from imbalanced-learn->imblearn)
  Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting scikit-learn<2,>=1.4.2 (from imbalanced-learn->imblearn)
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting sklearn-compat<0.2,>=0.1.6 (from imbalanced-learn->imblearn)
  Downloading sklearn_compat-0.1.6-py3-none-any.whl.metadata (22 kB)
Collecting joblib<2,>=1.2.0 (from imbalanced-learn->imblearn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl<4,>=2.0.0 (from imbalanced-learn->imblearn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting narwhals>=2.0.1 (from scikit-learn<2,>=1.4.2->imbalanced-learn->imblearn)
  Downloading narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Downloading imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Downloading imbalanced_learn-0.14.2-py3-none-any.whl (236 kB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 3.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/12.6 MB 3.4 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.6 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.6 MB 3.3 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 3.2 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 3.1 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.0 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 3.1 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 2.9 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 2.8 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.6 MB 2.7 MB/s eta 0:00:03
   -------------------- ------------------- 6.6/12.6 MB 2.6 MB/s eta 0:00:03
   --------------------- ------------------ 6.8/12.6 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.6 MB 2.4 MB/s eta 0:00:03
   ----------------------- ---------------- 7.3/12.6 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.6 MB 2.2 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.6 MB 2.2 MB/s eta 0:00:03
   -------------------------- ------------- 8.4/12.6 MB 2.2 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.6 MB 2.2 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.6 MB 2.2 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.6 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 2.4 MB/s  0:00:05
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.3 MB 2.3 MB/s eta 0:00:04
   --- ------------------------------------ 0.8/8.3 MB 1.9 MB/s eta 0:00:04
   ------ --------------------------------- 1.3/8.3 MB 2.1 MB/s eta 0:00:04
   -------- ------------------------------- 1.8/8.3 MB 2.2 MB/s eta 0:00:03
   ------------ --------------------------- 2.6/8.3 MB 2.3 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.3 MB 2.6 MB/s eta 0:00:02
   ------------------ --------------------- 3.9/8.3 MB 2.6 MB/s eta 0:00:02
   --------------------- ------------------ 4.5/8.3 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.3 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 6.3/8.3 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 7.3/8.3 MB 3.1 MB/s eta 0:00:01
   ------------------------------------- -- 7.9/8.3 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 2.7 MB/s  0:00:02
Downloading scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
    --------------------------------------- 0.5/37.3 MB 2.8 MB/s eta 0:00:14
   - -------------------------------------- 1.3/37.3 MB 3.3 MB/s eta 0:00:12
   -- ------------------------------------- 2.1/37.3 MB 3.4 MB/s eta 0:00:11
   -- ------------------------------------- 2.6/37.3 MB 3.3 MB/s eta 0:00:11
   --- ------------------------------------ 3.7/37.3 MB 3.6 MB/s eta 0:00:10
   ----- ---------------------------------- 5.0/37.3 MB 4.1 MB/s eta 0:00:08
   ------ --------------------------------- 6.0/37.3 MB 4.2 MB/s eta 0:00:08
   ------- -------------------------------- 7.3/37.3 MB 4.4 MB/s eta 0:00:07
   -------- ------------------------------- 8.4/37.3 MB 4.4 MB/s eta 0:00:07
   ---------- ----------------------------- 9.4/37.3 MB 4.5 MB/s eta 0:00:07
   ---------- ----------------------------- 10.2/37.3 MB 4.5 MB/s eta 0:00:07
   ------------ --------------------------- 11.3/37.3 MB 4.4 MB/s eta 0:00:06
   ------------- -------------------------- 12.3/37.3 MB 4.5 MB/s eta 0:00:06
   -------------- ------------------------- 13.1/37.3 MB 4.5 MB/s eta 0:00:06
   -------------- ------------------------- 13.4/37.3 MB 4.3 MB/s eta 0:00:06
   -------------- ------------------------- 13.9/37.3 MB 4.1 MB/s eta 0:00:06
   --------------- ------------------------ 14.7/37.3 MB 4.0 MB/s eta 0:00:06
   ---------------- ----------------------- 15.2/37.3 MB 4.0 MB/s eta 0:00:06
   ---------------- ----------------------- 15.7/37.3 MB 3.9 MB/s eta 0:00:06
   ----------------- ---------------------- 16.5/37.3 MB 3.9 MB/s eta 0:00:06
   ------------------ --------------------- 17.3/37.3 MB 3.9 MB/s eta 0:00:06
   ------------------- -------------------- 18.1/37.3 MB 3.8 MB/s eta 0:00:05
   ------------------- -------------------- 18.1/37.3 MB 3.8 MB/s eta 0:00:05
   ------------------- -------------------- 18.6/37.3 MB 3.6 MB/s eta 0:00:06
   -------------------- ------------------- 18.9/37.3 MB 3.6 MB/s eta 0:00:06
   -------------------- ------------------- 19.1/37.3 MB 3.5 MB/s eta 0:00:06
   --------------------- ------------------ 19.7/37.3 MB 3.4 MB/s eta 0:00:06
   --------------------- ------------------ 20.2/37.3 MB 3.4 MB/s eta 0:00:06
   ---------------------- ----------------- 21.0/37.3 MB 3.3 MB/s eta 0:00:05
   ----------------------- ---------------- 21.5/37.3 MB 3.3 MB/s eta 0:00:05
   ----------------------- ---------------- 22.0/37.3 MB 3.3 MB/s eta 0:00:05
   ------------------------ --------------- 22.8/37.3 MB 3.3 MB/s eta 0:00:05
   ------------------------- -------------- 23.3/37.3 MB 3.3 MB/s eta 0:00:05
   -------------------------- ------------- 24.4/37.3 MB 3.3 MB/s eta 0:00:04
   -------------------------- ------------- 24.9/37.3 MB 3.3 MB/s eta 0:00:04
   --------------------------- ------------ 25.7/37.3 MB 3.3 MB/s eta 0:00:04
   ---------------------------- ----------- 26.5/37.3 MB 3.3 MB/s eta 0:00:04
   ----------------------------- ---------- 27.3/37.3 MB 3.3 MB/s eta 0:00:03
   ------------------------------ --------- 28.0/37.3 MB 3.4 MB/s eta 0:00:03
   ------------------------------ --------- 28.6/37.3 MB 3.4 MB/s eta 0:00:03
   ------------------------------- -------- 29.1/37.3 MB 3.3 MB/s eta 0:00:03
   ------------------------------- -------- 29.4/37.3 MB 3.3 MB/s eta 0:00:03
   -------------------------------- ------- 29.9/37.3 MB 3.2 MB/s eta 0:00:03
   -------------------------------- ------- 30.7/37.3 MB 3.2 MB/s eta 0:00:03
   --------------------------------- ------ 31.2/37.3 MB 3.2 MB/s eta 0:00:02
   ---------------------------------- ----- 32.0/37.3 MB 3.2 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/37.3 MB 3.2 MB/s eta 0:00:02
   ----------------------------------- ---- 33.6/37.3 MB 3.3 MB/s eta 0:00:02
   ------------------------------------ --- 34.3/37.3 MB 3.3 MB/s eta 0:00:01
   ------------------------------------- -- 35.1/37.3 MB 3.3 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 3.2 MB/s  0:00:11
Downloading sklearn_compat-0.1.6-py3-none-any.whl (22 kB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading narwhals-2.24.0-py3-none-any.whl (461 kB)
Installing collected packages: threadpoolctl, numpy, narwhals, joblib, scipy, scikit-learn, sklearn-compat, imbalanced-learn, imblearn

   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   ---- ----------------------------------- 1/9 [numpy]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   -------- ------------------------------- 2/9 [narwhals]
   ------------- -------------------------- 3/9 [joblib]
   ------------- -------------------------- 3/9 [joblib]
   ------------- -------------------------- 3/9 [joblib]
   ------------- -------------------------- 3/9 [joblib]
   ------------- -------------------------- 3/9 [joblib]
   ------------- -------------------------- 3/9 [joblib]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]
   ----------------- ---------------------- 4/9 [scipy]

In [26]:
from imblearn.over_sampling import SMOTE

In [27]:
smote=SMOTE(k_neighbors=5)

In [28]:
x_res,y_res=smote.fit_resample(x,y)

In [29]:
y_res.value_counts()

CLASS
High      72
Low       72
Medium    72
Name: count, dtype: int64

In [32]:
from sklearn.feature_selection import SelectKBest,chi2

In [33]:
skf=SelectKBest(k=5,score_func=chi2)

In [34]:
x_new=skf.fit_transform(x_res,y_res)

In [35]:
x_new.shape

(216, 5)

In [37]:
skf.get_support()

array([ True, False, False, False, False, False, False, False,  True,
       False, False,  True,  True, False, False, False, False,  True,
       False, False])

In [38]:
skf.get_feature_names_out()

array(['COLOR_INTENSITY', 'FLAVANOIDS', 'PROLINE', 'TEMPERATURE',
       'FER_P2O5_PER'], dtype=object)

In [39]:
x=x_res.loc[:,skf.get_support()]

In [40]:
x;

In [41]:
x.shape,y_res.shape

((216, 5), (216,))

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y_res,
                                              random_state=0,
                                              test_size=0.2,
                                              stratify=y_res)

In [43]:
from sklearn.preprocessing import MinMaxScaler
sca=MinMaxScaler()
x_train_scaled=sca.fit_transform(x_train)
x_test_scaled=sca.transform(x_test)

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [45]:
params={
    'random_state':[0,42],
    'criterion':['gini','entropy'],
    'max_features':['sqrt','log2'],
    'n_estimators':[20,30,100]
}

In [46]:
grid=GridSearchCV(estimator=RandomForestClassifier(),
                 param_grid=params,
                 scoring='accuracy',
                 cv=5)

In [47]:
grid.fit(x_train_scaled,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [20, 30, 100],
                         'random_state': [0, 42]},
             scoring='accuracy')

In [48]:
y_pred=grid.predict(x_test_scaled)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(y_test,y_pred)

0.9545454545454546

In [52]:
import joblib

In [53]:
joblib.dump(grid,'rf_classifier.pkl')

['rf_classifier.pkl']

In [55]:
joblib.dump(sca,'rf_scaler.pkl')

['rf_scaler.pkl']

In [56]:
import os

print(os.getcwd())

C:\Users\Akshata